In [1]:
from line_loading import calc_line_loads
%load_ext autoreload
%autoreload 2
import line_loading

In [33]:
df=calc_line_loads()

Unit permanent loads (kN/m^2):

          Structure  Substrates  Finishes   Partitions  Total Gk
Roof           0.50        0.45      0.60         0.00      1.55
Tim Flr        0.11        0.31      0.08         0.75      1.25
Int Leaf       1.50        0.15      0.10         0.00      1.75
Ext Leaf       2.15        0.00      0.00         0.00      2.15
Int Wall       1.50        0.30      0.20         0.00      2.00
Grd Flr        3.60        0.00      0.15         0.75      4.50
Test           1.00        0.00      0.00         0.00      1.00

Supported lengths (m):

         Roof  Tim Flr  Int Leaf  Ext Leaf  Int Wall  Grd Flr  Test
Element
Line A      1        2         3         4         5        6     7