In [1]:
from line_loading import calc_line_loads
%load_ext autoreload
%autoreload 2
import line_loading

In [68]:
df=calc_line_loads()

Unit permanent loads (kN/m^2):

          Structure  Substrates  Finishes   Partitions  Total gk
Roof           0.50        0.45      0.60         0.00      1.55
Tim Flr        0.11        0.31      0.08         0.75      1.25
Int Leaf       1.50        0.15      0.10         0.00      1.75
Ext Leaf       2.15        0.00      0.00         0.00      2.15
Int Wall       1.50        0.30      0.20         0.00      2.00
Grd Flr        3.60        0.00      0.15         0.75      4.50

Unit variable loads (kN/m^2):

           qk
Roof      0.6
Tim Flr   1.5
Int Leaf  0.0
Ext Leaf  0.0
Int Wall  0.0
Grd Flr   1.5

Supported lengths (m):

          Roof  Tim Flr  Int Leaf  Ext Leaf  Int Wall  Grd Flr
Elements
Line A       5        2         6         6         0        2

Permanent load composition (kN/m):

          Line A
Roof        7.75
Tim Flr     2.50
Int Leaf   10.50
Ext Leaf   12.90
Int Wall    0.00
Grd Flr     9.00
Total Gk   42.65

Variable load composition (kN/m):

          Line A
Roof         3.0
Tim Flr      3.0
Int Leaf     0.0
Ext Leaf     0.0
Int Wall     0.0
Grd Flr      3.0
Total Qk     9.0

Load summary (kN/m):

           Gk   Qk
Line A  42.65  9.0